name: Deploy Rom Search
on:
  push:
    branches:
      - main  # 当你修改并提交 main 分支的代码时触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.' # 把整个仓库的文件打包上传

      - name: Deploy
        uses: actions/deploy-pages@v2
